import React from "react";
import "./tourgrid.css";

const TourGrid = () => {
  return (
    <div className="containerr h-100">
      <div className="row align-items-center h-100">
        <div className="slider">
          <div className="logos">
            <i className="fab fa-js fa-4x"></i>
            <i className="fab fa-linkedin-in fa-4x"></i>
            <i className="fab fa-dribbble fa-4x"></i>
            <i className="fab fa-medium-m fa-4x"></i>
            <i className="fab fa-github fa-4x"></i>
            <img
              className="logos-images"
              src="./src/assets/Frame1.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame2.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame3.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame4.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame5.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame6.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame1.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame2.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame3.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame4.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame5.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame6.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame1.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame2.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame3.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame4.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame5.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame6.svg"
              alt=""
            />

            <img
              className="logos-images"
              src="./src/assets/Frame1.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame2.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame3.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame4.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame5.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame6.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame1.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame2.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame3.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame4.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame5.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame6.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame1.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame2.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame3.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame4.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame5.svg"
              alt=""
            />
            <img
              className="logos-images"
              src="./src/assets/Frame6.svg"
              alt=""
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default TourGrid;
